name: Xunit api tester

on:
  push:
    branches:
      - Main
      - DevBranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3


     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
          dotnet-version: 8.x

     - name: Restore Dependencies
       run: dotnet restore

     - name: Build soulution
       run: dotnet build --no-restore --configuration debug

     - name: run tests
       run: dotnet test --no-build --configuration debug --verbosity diagnostic
       continue-on-error: false
